---
title: "p8105_hw1_sp3804"
author: "Shannon (Seonyoung Park) (sp3804)"
date: "9/15/2020"
output: github_document
---

This is my solution to HW1

```{r setup, include=FALSE}
library(tidyverse)
```

## Problem 1

Creat a data frame with the specified elements.

```{r}
prob1_df = 
  tibble(
  samp = rnorm(10),
  samp_gt_0 = samp > 0,
  char_vec = c("a","b","c","d","e","f","g","h","i","j"),
  factor_vec = factor(c("low","low","low","mod","mod","mod","high","high","high","high"))
)
```

Take the mean of each variable in my data frame.

```{r}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_gt_0)) #mean = 0.6 (?)
mean(pull(prob1_df, char_vec)) #not possible (x numeric)
mean(pull(prob1_df, factor_vec)) #not possible (x numeric)
```
I can take the mean of number but not character or factor.

```{r}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_gt_0)) 
as.numeric(pull(prob1_df, char_vec)) 
as.numeric(pull(prob1_df, factor_vec)) 
```
```{r}
as.numeric(pull(prob1_df, samp_gt_0))*pull(prob1_df,samp)
```


## Problem 2

```{r}
data("penguins", package = "palmerpenguins")

```

